# .goreleaser.yml
# Build customization
project_name: tfprettyplan

before:
  hooks:
    - go mod tidy

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: windows
        goarch: arm64
    main: ./cmd/tfprettyplan
    ldflags:
      - -s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{.Date}}
    binary: tfprettyplan

archives:
  - format: tar.gz
    # Use zip for Windows
    format_overrides:
      - goos: windows
        format: zip
    name_template: >-
      {{ .ProjectName }}_{{ .Version }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
    files:
      - README.md
      - LICENSE*
      - docs/*

checksum:
  name_template: 'checksums.txt'

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^ci:'
      - Merge pull request
      - Merge branch

release:
  prerelease: auto
  name_template: "{{ .ProjectName }} v{{ .Version }}"

brews:
  - name: tfprettyplan
    homepage: "https://github.com/ao/tfprettyplan"
    description: "A command-line tool that renders Terraform plan files in a more human-readable format"
    license: "MIT"
    tap:
      owner: ao
      name: homebrew-tap
    commit_author:
      name: goreleaserbot
      email: goreleaser@github.com
    folder: Formula
    install: |
      bin.install "tfprettyplan"
    test: |
      system "#{bin}/tfprettyplan", "-version"

